// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RecycleCoin.UI.Context;

#nullable disable

namespace RecycleCoin.UI.Migrations
{
    [DbContext(typeof(RecycleCoinDbContext))]
    [Migration("20221220144736_UserUpdate")]
    partial class UserUpdate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("RecycleCoin.UI.Models.Aluminum", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("CarbonValue")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Object")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Aluminums");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9b4900f3-f9ce-40dc-aa58-4fe0c681c331"),
                            CarbonValue = 330m,
                            Object = "Kola Kutusu"
                        });
                });

            modelBuilder.Entity("RecycleCoin.UI.Models.Iron", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("CarbonValue")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Object")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Irons");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6784cd47-bccc-4ddd-a38d-75401374b9f5"),
                            CarbonValue = 400m,
                            Object = "Pil"
                        });
                });

            modelBuilder.Entity("RecycleCoin.UI.Models.Paper", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("CarbonValue")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Object")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Papers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7eb84f85-459e-4417-bbc9-1654ecb84c63"),
                            CarbonValue = 50m,
                            Object = "Gazete"
                        });
                });

            modelBuilder.Entity("RecycleCoin.UI.Models.Pine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("CarbonValue")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Object")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Pines");

                    b.HasData(
                        new
                        {
                            Id = new Guid("70108e90-c3c2-480e-956f-504b222371e4"),
                            CarbonValue = 200m,
                            Object = "Gazoz Şisesi"
                        });
                });

            modelBuilder.Entity("RecycleCoin.UI.Models.Plastic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("CarbonValue")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Object")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Plastics");

                    b.HasData(
                        new
                        {
                            Id = new Guid("83ac8f5f-e9a7-46dc-acbc-ccc0b601c241"),
                            CarbonValue = 50m,
                            Object = "Su Şişesi"
                        });
                });

            modelBuilder.Entity("RecycleCoin.UI.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Identity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("RecycleCoinAccount")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("Roles")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("68e2b0d9-00b3-4e92-809a-a0ffc9a5fcd8"),
                            FullName = "Admin",
                            Identity = "17B8B50331A934BD2821B15FE88FB3B8AF0CA093D86B0757ED70DD4F0F868619",
                            Password = "Admin",
                            RecycleCoinAccount = 0m,
                            Roles = 1,
                            UserName = "Admin"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
