// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RecycleCoin.UI.Context;

#nullable disable

namespace RecycleCoin.UI.Migrations
{
    [DbContext(typeof(RecycleCoinDbContext))]
    [Migration("20221220142509_CreateDatabase")]
    partial class CreateDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("RecycleCoin.UI.Models.Aluminum", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("CarbonValue")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Object")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Aluminums");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d4b4102d-9ebf-41cb-bbed-91f324339818"),
                            CarbonValue = 330m,
                            Object = "Kola Kutusu"
                        });
                });

            modelBuilder.Entity("RecycleCoin.UI.Models.Iron", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("CarbonValue")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Object")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Irons");

                    b.HasData(
                        new
                        {
                            Id = new Guid("09f78b5e-0b17-4d4c-b0e4-c2f31ee62b5e"),
                            CarbonValue = 400m,
                            Object = "Pil"
                        });
                });

            modelBuilder.Entity("RecycleCoin.UI.Models.Paper", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("CarbonValue")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Object")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Papers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4c3ab4f3-4696-440d-bf43-09c8e5fe87c3"),
                            CarbonValue = 50m,
                            Object = "Gazete"
                        });
                });

            modelBuilder.Entity("RecycleCoin.UI.Models.Pine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("CarbonValue")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Object")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Pines");

                    b.HasData(
                        new
                        {
                            Id = new Guid("20046759-c2f9-4ff7-9b60-93b9da00504a"),
                            CarbonValue = 200m,
                            Object = "Gazoz Şisesi"
                        });
                });

            modelBuilder.Entity("RecycleCoin.UI.Models.Plastic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("CarbonValue")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Object")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Plastics");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f337de15-3cfc-473e-b551-e0ca14c0251c"),
                            CarbonValue = 50m,
                            Object = "Su Şişesi"
                        });
                });

            modelBuilder.Entity("RecycleCoin.UI.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("CarbonAccount")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Identity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("RecycleCoinAccount")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("Roles")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3d9c78f6-6ac2-4e4b-a9a4-b2202e10768a"),
                            CarbonAccount = 0m,
                            FullName = "Admin",
                            Identity = "A6AFE2EF9641A327692BD71B4917FB45FC0302023928A8FA73E8A9F69162337B",
                            Password = "Admin",
                            RecycleCoinAccount = 0m,
                            Roles = 1,
                            UserName = "Admin"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
